android:
  config:
    "dynatrace {
      configurations {
        defaultConfig {
          autoStart{
            applicationId 'ad23bfb5-2f5d-463f-aeb2-27a958115003'
            beaconUrl 'https://MLW-DTSESSION.CORP.MOI.GOV:443/mbeacon/06714fab-00ca-4cd6-92fc-bcce1c6af14e'
          }
          userOptIn true
        }
      }
    }"

ios:
  config:
    "<key>DTXApplicationID</key>
    <string>ad23bfb5-2f5d-463f-aeb2-27a958115003</string>
    <key>DTXBeaconURL</key>
    <string>https://MLW-DTSESSION.CORP.MOI.GOV:443/mbeacon/06714fab-00ca-4cd6-92fc-bcce1c6af14e</string>
    <key>DTXUserOptIn</key>
    <true/>"
